// Code generated by capnpc-go. DO NOT EDIT.

package capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type TriTemporalEvent capnp.Struct

// TriTemporalEvent_TypeID is the unique identifier for the type TriTemporalEvent.
const TriTemporalEvent_TypeID = 0xbeb44ec2f6a3f8ae

func NewTriTemporalEvent(s *capnp.Segment) (TriTemporalEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return TriTemporalEvent(st), err
}

func NewRootTriTemporalEvent(s *capnp.Segment) (TriTemporalEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2})
	return TriTemporalEvent(st), err
}

func ReadRootTriTemporalEvent(msg *capnp.Message) (TriTemporalEvent, error) {
	root, err := msg.Root()
	return TriTemporalEvent(root.Struct()), err
}

func (s TriTemporalEvent) String() string {
	str, _ := text.Marshal(0xbeb44ec2f6a3f8ae, capnp.Struct(s))
	return str
}

func (s TriTemporalEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (TriTemporalEvent) DecodeFromPtr(p capnp.Ptr) TriTemporalEvent {
	return TriTemporalEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s TriTemporalEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s TriTemporalEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s TriTemporalEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s TriTemporalEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s TriTemporalEvent) Latitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s TriTemporalEvent) SetLatitude(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s TriTemporalEvent) Longitude() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s TriTemporalEvent) SetLongitude(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s TriTemporalEvent) AssertionTime() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s TriTemporalEvent) SetAssertionTime(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s TriTemporalEvent) EntityId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s TriTemporalEvent) HasEntityId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s TriTemporalEvent) EntityIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s TriTemporalEvent) SetEntityId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s TriTemporalEvent) Payload() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s TriTemporalEvent) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s TriTemporalEvent) PayloadBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s TriTemporalEvent) SetPayload(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// TriTemporalEvent_List is a list of TriTemporalEvent.
type TriTemporalEvent_List = capnp.StructList[TriTemporalEvent]

// NewTriTemporalEvent creates a new list of TriTemporalEvent.
func NewTriTemporalEvent_List(s *capnp.Segment, sz int32) (TriTemporalEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 2}, sz)
	return capnp.StructList[TriTemporalEvent](l), err
}

// TriTemporalEvent_Future is a wrapper for a TriTemporalEvent promised by a client call.
type TriTemporalEvent_Future struct{ *capnp.Future }

func (f TriTemporalEvent_Future) Struct() (TriTemporalEvent, error) {
	p, err := f.Future.Ptr()
	return TriTemporalEvent(p.Struct()), err
}

type CRDTDeltaEvent capnp.Struct

// CRDTDeltaEvent_TypeID is the unique identifier for the type CRDTDeltaEvent.
const CRDTDeltaEvent_TypeID = 0xa90774c0daa3fdc7

func NewCRDTDeltaEvent(s *capnp.Segment) (CRDTDeltaEvent, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return CRDTDeltaEvent(st), err
}

func NewRootCRDTDeltaEvent(s *capnp.Segment) (CRDTDeltaEvent, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5})
	return CRDTDeltaEvent(st), err
}

func ReadRootCRDTDeltaEvent(msg *capnp.Message) (CRDTDeltaEvent, error) {
	root, err := msg.Root()
	return CRDTDeltaEvent(root.Struct()), err
}

func (s CRDTDeltaEvent) String() string {
	str, _ := text.Marshal(0xa90774c0daa3fdc7, capnp.Struct(s))
	return str
}

func (s CRDTDeltaEvent) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CRDTDeltaEvent) DecodeFromPtr(p capnp.Ptr) CRDTDeltaEvent {
	return CRDTDeltaEvent(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CRDTDeltaEvent) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CRDTDeltaEvent) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CRDTDeltaEvent) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CRDTDeltaEvent) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CRDTDeltaEvent) Version() uint16 {
	return capnp.Struct(s).Uint16(0)
}

func (s CRDTDeltaEvent) SetVersion(v uint16) {
	capnp.Struct(s).SetUint16(0, v)
}

func (s CRDTDeltaEvent) PayloadDigest() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s CRDTDeltaEvent) HasPayloadDigest() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CRDTDeltaEvent) SetPayloadDigest(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s CRDTDeltaEvent) OriginNodeID() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s CRDTDeltaEvent) HasOriginNodeID() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CRDTDeltaEvent) SetOriginNodeID(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s CRDTDeltaEvent) DotNodeID() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s CRDTDeltaEvent) HasDotNodeID() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s CRDTDeltaEvent) SetDotNodeID(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s CRDTDeltaEvent) DotCounter() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s CRDTDeltaEvent) SetDotCounter(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s CRDTDeltaEvent) H3Index() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s CRDTDeltaEvent) SetH3Index(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

func (s CRDTDeltaEvent) SystemTime() int64 {
	return int64(capnp.Struct(s).Uint64(24))
}

func (s CRDTDeltaEvent) SetSystemTime(v int64) {
	capnp.Struct(s).SetUint64(24, uint64(v))
}

func (s CRDTDeltaEvent) ValidTimeStart() int64 {
	return int64(capnp.Struct(s).Uint64(32))
}

func (s CRDTDeltaEvent) SetValidTimeStart(v int64) {
	capnp.Struct(s).SetUint64(32, uint64(v))
}

func (s CRDTDeltaEvent) ValidTimeEnd() int64 {
	return int64(capnp.Struct(s).Uint64(40))
}

func (s CRDTDeltaEvent) SetValidTimeEnd(v int64) {
	capnp.Struct(s).SetUint64(40, uint64(v))
}

func (s CRDTDeltaEvent) AssertionTime() int64 {
	return int64(capnp.Struct(s).Uint64(48))
}

func (s CRDTDeltaEvent) SetAssertionTime(v int64) {
	capnp.Struct(s).SetUint64(48, uint64(v))
}

func (s CRDTDeltaEvent) DecisionTime() int64 {
	return int64(capnp.Struct(s).Uint64(56))
}

func (s CRDTDeltaEvent) SetDecisionTime(v int64) {
	capnp.Struct(s).SetUint64(56, uint64(v))
}

func (s CRDTDeltaEvent) EntityId() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s CRDTDeltaEvent) HasEntityId() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s CRDTDeltaEvent) EntityIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s CRDTDeltaEvent) SetEntityId(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s CRDTDeltaEvent) Payload() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s CRDTDeltaEvent) HasPayload() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s CRDTDeltaEvent) PayloadBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s CRDTDeltaEvent) SetPayload(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

// CRDTDeltaEvent_List is a list of CRDTDeltaEvent.
type CRDTDeltaEvent_List = capnp.StructList[CRDTDeltaEvent]

// NewCRDTDeltaEvent creates a new list of CRDTDeltaEvent.
func NewCRDTDeltaEvent_List(s *capnp.Segment, sz int32) (CRDTDeltaEvent_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 64, PointerCount: 5}, sz)
	return capnp.StructList[CRDTDeltaEvent](l), err
}

// CRDTDeltaEvent_Future is a wrapper for a CRDTDeltaEvent promised by a client call.
type CRDTDeltaEvent_Future struct{ *capnp.Future }

func (f CRDTDeltaEvent_Future) Struct() (CRDTDeltaEvent, error) {
	p, err := f.Future.Ptr()
	return CRDTDeltaEvent(p.Struct()), err
}

type CRDTDeltaBatch capnp.Struct

// CRDTDeltaBatch_TypeID is the unique identifier for the type CRDTDeltaBatch.
const CRDTDeltaBatch_TypeID = 0x8832c13e5bbfaa0c

func NewCRDTDeltaBatch(s *capnp.Segment) (CRDTDeltaBatch, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CRDTDeltaBatch(st), err
}

func NewRootCRDTDeltaBatch(s *capnp.Segment) (CRDTDeltaBatch, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return CRDTDeltaBatch(st), err
}

func ReadRootCRDTDeltaBatch(msg *capnp.Message) (CRDTDeltaBatch, error) {
	root, err := msg.Root()
	return CRDTDeltaBatch(root.Struct()), err
}

func (s CRDTDeltaBatch) String() string {
	str, _ := text.Marshal(0x8832c13e5bbfaa0c, capnp.Struct(s))
	return str
}

func (s CRDTDeltaBatch) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CRDTDeltaBatch) DecodeFromPtr(p capnp.Ptr) CRDTDeltaBatch {
	return CRDTDeltaBatch(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CRDTDeltaBatch) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CRDTDeltaBatch) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CRDTDeltaBatch) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CRDTDeltaBatch) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CRDTDeltaBatch) Events() (CRDTDeltaEvent_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return CRDTDeltaEvent_List(p.List()), err
}

func (s CRDTDeltaBatch) HasEvents() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CRDTDeltaBatch) SetEvents(v CRDTDeltaEvent_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewEvents sets the events field to a newly
// allocated CRDTDeltaEvent_List, preferring placement in s's segment.
func (s CRDTDeltaBatch) NewEvents(n int32) (CRDTDeltaEvent_List, error) {
	l, err := NewCRDTDeltaEvent_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return CRDTDeltaEvent_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// CRDTDeltaBatch_List is a list of CRDTDeltaBatch.
type CRDTDeltaBatch_List = capnp.StructList[CRDTDeltaBatch]

// NewCRDTDeltaBatch creates a new list of CRDTDeltaBatch.
func NewCRDTDeltaBatch_List(s *capnp.Segment, sz int32) (CRDTDeltaBatch_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[CRDTDeltaBatch](l), err
}

// CRDTDeltaBatch_Future is a wrapper for a CRDTDeltaBatch promised by a client call.
type CRDTDeltaBatch_Future struct{ *capnp.Future }

func (f CRDTDeltaBatch_Future) Struct() (CRDTDeltaBatch, error) {
	p, err := f.Future.Ptr()
	return CRDTDeltaBatch(p.Struct()), err
}

const schema_eb5b7e1f3a9c4d27 = "x\xda\x8c\xd2\xcfk\x1ce\x1c\x06\xf0\xe7y\xdf\x99L" +
	"\xd2\xec\x1a\x87\x99\xa3\xb2\x17E<(j=\xe5`$" +
	"M\x0e[0t2+\x88\xa5\xe0\xb0\xf3\x92\x1d\xd9\x9d" +
	"Yg\xde,]I\x0d\x85\x14rh\xa1\x87\x14rh" +
	"\xa1\xd0\x0a**=(x\x10\x7f]\xfc\x1f\xbc\x08\xbd" +
	"z\xf3 ^d\xe4;d\xb7iE\xe8m\xe7\xb3\xcf" +
	"~\xf7\xfb\xbe\xf3\xbcv\xc4\xb7\x9d\xd7\xdb\x85\x82\x8a\x9e" +
	"s\x17\xea\xd6\x17?^|\xeb\xe77\x0e\xe1\xb7Y\xbf" +
	"\xf4\xce\xed\xd5\xce'\x17\xff\x80K\x0f\x08\x9e\xe7\xc3\xe0" +
	"\xe5\xe6\xd3\x8b\\\x03\xeb_\xff\xb9\xf7\xdbO\xd6\xfb\x1c" +
	"Q\x9b\x8b\xa7\xc2\xaeD\xde\xe5\xc3 \x91\xf0\xd9K\xfc" +
	"]\x81\xf5\xd7\x7f\xdf\xfb\xeb\x97\xado~\x90\xb4>\x95" +
	"V\x92\xdeu\xfe\x0c\xae:\x92\xbe\xe2t\x88W\xea\xaa" +
	"?0\xa3\xe4\xd5\xbeJ\xc6\xf9x\xf5\xdc\xf6Fo\xc3" +
	"\x0cm\xb2\x9ex\xb6?\xb8@F\x8ev\x00\x87\x80\xdf" +
	"^\x05\xa2E\xcd\xe8\x05\xc5531\xb9\xad\xf8\x0cx" +
	"A\x93\xcf>\xda\x11\x14\xfc\xbf\xb9\x9b\x13\xcf\xe4V\xe6" +
	"\xbe9\x9b\x1b\\\xe2:\x10\xbfG\xcd8\xa5\"\x19R" +
	"8a\x09\xc4\x1f\x08\x0f\xa9\xe8+\x86T@\x90\xf1C" +
	" \x1e\x88[q\xadBj \xf8\x88\xdb@<\x16\xdf" +
	"\x13w\x18\xd2\x01\x82)\xdf\x07\xe2\xcb\xe2\x07\xe2\xae\x0a" +
	"\xe9\x02\xc1\xd5\xe6o\xf7\xc4\x0f\xc5\x17t\xc8\x05 \xb8" +
	"\xd6\xe4\x0f\xc4o\x8a{N\xd8\xbc\x8b\x1b\xfc\x18\x88\xaf" +
	"\x8b\x1f\x8b/\xba!\x17\x81\xe0V\xb3\xcf\x91\xf8]\xf1" +
	"\xa5\x85\x90K@p\xa7\xd9\xff\xb6\xf8g\xe2g\xbc\x90" +
	"g\x80\xe0\xd3&\x7f_\xfc\x81\xf8\xb2\x0e\xb9\x0c\x04_" +
	"\xf1<\x10\x7f)\xfe\x9dx\xcb\x09\xd9\x02\x82o\x9b=" +
	"\x1f\x88\x7fO\xc5\xfd\x89)\xab\xac\xc8\xe9A\xd1\x03\xeb" +
	"q2\x1d\x16I\xba\x81N\xb6c*\xcb6\x14\xdb`" +
	"]\x94\xd9N\x96o\x15XIMwc\xceia\xb7" +
	"\x8a\xd4t\xc1\xc7\xec\\\xb1\x9b[hSr\x09\x8aK" +
	"\xe0\xfe\xe0l7O\xcd\xe5\xd9s]M+kF\xbd" +
	"\x0czd\xe8B\xd1\x05\xebI2\xcc\xd2^6\xc2\x9a" +
	"\x89mR\xda\xff~\xb1b6\xf3t\xceIU\x99\xd2" +
	"f\x05:y/;5'5\xfdLN\x85\x95\xc7\xd8" +
	"\xe46\xb3\xd3n\x0a\x80-(\xb6\xc0\xfd\x93\xf3\xce\x9e" +
	"\x9fhZ\xaf\xcczf4.\xcad\xd8\xd9\x9c\x9ct" +
	"-\x9cw\xf8\xcay \xda\xd3\x8c\x0e\x15\xfd\x93\xa6\xf9" +
	"\xd7\xb6\x81\xe8@3\xba)5SM\xcd\xfc\x1b%\x10" +
	"]\xd7\x8c\x8e\x15\xa9\x9b\x8a\xf9\xb7\xe4\xd7G\x9a\xd1\xdd" +
	"G\xfd\xf2\xef\xac\x03\xd1\xb1ft_\xb1\x1e&6\xb3" +
	"\xbb\xa9\x91\x85\x97\xa1\xb8\x0c\xd6\xc3\"\xdf\x11\x04\xcd\xdc" +
	"\x9e\xbc\x87\xd9%?\xc5\x81\xff\x0d\x00\x00\xff\xff\xf7\xd6" +
	"\xe8q"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_eb5b7e1f3a9c4d27,
		Nodes: []uint64{
			0x8832c13e5bbfaa0c,
			0xa90774c0daa3fdc7,
			0xbeb44ec2f6a3f8ae,
		},
		Compressed: true,
	})
}
